language: perl
sudo: false

addons:
  postgresql: "9.3"

perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"

env:
  global:
    - PG_PORT=5432


branches:
  except:
    - releases

before_install:
  - git config --global user.name "TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
  - git fetch --unshallow || true
  - git fetch origin master:master
  #- git fetch origin releases:releases
  - git clone --depth=1 git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - '[ `perlbrew lib list` ] || perlbrew lib create travis'
  - perlbrew use $PERLBREW_PERL@travis
  - perl -V
  - cpan-install ExtUtils::MakeMaker~6.31 Dist::Zilla
  - "cpan-install $(dzil authordeps --missing --versions | grep -v '^inc::' | sed -e's/ = 0$//' -e's/ = /~/')"
  #- dzil build --in="$(pwd)/build_dir"
  #- cd build_dir

install:
  - cpanm --dev PMLTQ
  #- cpan-install Sys::SigAction
  - "cpan-install $(dzil listdeps --missing --versions | grep -v '^inc::' | sed -e's/ = 0$//' -e's/ = /~/')"
  - "cpan-install $(dzil listdeps --develop --missing --versions | grep -v '^inc::' | sed -e's/ = 0$//' -e's/ = /~/')"
  - cpan-install --deps
  - cpan-install --coverage

before_script:
  - coverage-setup

script:
  # - prove -j$(test-jobs) $(test-files)   # parallel testing
  - dzil test -j$(test-jobs)

after_success:
  - coverage-report

cache:
  directories:
    - $PERLBREW_HOME/libs

notifications:
  email:
    recipients:
      - kopp@ufal.mff.cuni.cz
    on_success: change
    on_failure: always
